[blazar] add overwrite external service endpoints
ChameleonCloud/chi-in-a-box pull request #135
Opened 2021-12-07 17:31 UTC by zhenz

2021-12-08 15:10 UTC, diurnalist requested changes

2021-12-08 15:10 UTC, diurnalist commented on kolla/node_custom_config/blazar.conf
> +{% if blazar_external_service_endpoint is defined %}
I think we should also default this to some values in the defaults.yml, b/c most sites are not going to deviate.

```yaml
blazar_external_service_check_create_endpoint: "{{ chameleon_portal_url }}/balance/check-create/"
... etc
```

2021-12-09 17:20 UTC, msherman64 reviewed
Looks good to me. Does this require any changes to the site config?

2021-12-09 17:23 UTC, zhenz commented
> Looks good to me. Does this require any changes to the site config?

I don't think so, as Jason asked me to add defaults.

2021-12-09 17:51 UTC, msherman64 approved these changes

2021-12-09 18:14 UTC, diurnalist approved these changes

2021-12-09 18:16 UTC, merged