support for glance multi store
ChameleonCloud/chi-in-a-box pull request #168
Opened 2022-03-29 19:47 UTC by zhenz

2022-04-05 15:54 UTC, msherman64 requested changes
overall looks good, just want to doublecheck variable naming and add docs.

2022-04-05 15:54 UTC, msherman64 commented on kolla/node_custom_config/glance.conf
> +enabled_backends = {% for key in glance_store_backends %}{{ key.name }}:{{ key.type }}{% if not loop.last %}, {% endif %}{% endfor %}
should this be `glance_backends` instead of `glance_store_backends`?

2022-04-05 15:54 UTC, msherman64 commented on kolla/node_custom_config/glance.conf
> +filesystem_store_datadir = /var/lib/glance
this looks like it should be `filesystem_store_datadir = /var/lib/glance/images/`

which is already set in the kolla defaults https://github.com/ChameleonCloud/kolla-ansible/blob/dbe349d720eaef838597845e7d1202a163bf79d5/ansible/roles/glance/templates/glance-api.conf.j2#L57

It needs to store images in a subdirectory of the volume, since the volume is also used for image caching and other purposes.

2022-04-05 15:54 UTC, msherman64 commented on kolla/node_custom_config/glance.conf
> +{% endif %}
Is it intended that all sites have write access to the swift container? If the swift bucket is set to public, sites could access it read only via the http store type.

2022-04-05 15:54 UTC, msherman64 commented on kolla/defaults.yml
> +glance_file_datadir_volume: /var/lib/glance
Could you add this line, with a comment, to both the example configuration, and the documentation?
A couple of sites are interested in placing this directory on shared storage, and that's currently not in our documentation.

upstream docs: https://docs.openstack.org/kolla-ansible/train/reference/shared-services/glance-guide.html#file-backend

2022-04-07 01:13 UTC, zhenz commented on kolla/node_custom_config/glance.conf
> +filesystem_store_datadir = /var/lib/glance
the kolla defaults has it under the `glance_store` section, but for multi-store, I need to put it under the `file` section. I've updated it to `/var/lib/glance/images/`.

2022-04-07 01:15 UTC, zhenz commented on kolla/node_custom_config/glance.conf
> +enabled_backends = {% for key in glance_store_backends %}{{ key.name }}:{{ key.type }}{% if not loop.last %}, {% endif %}{% endfor %}
the upstream has it as `glance_store_backends`

2022-04-07 01:17 UTC, zhenz commented on kolla/node_custom_config/glance.conf
> +{% endif %}
we'd like to have the `chameleon-images` swift container be public -- all sites can list the container and download from the container without credetials, but they can't upload to the container.

2022-04-07 01:17 UTC, zhenz commented on kolla/defaults.yml
> +glance_file_datadir_volume: /var/lib/glance
added.

2022-04-07 14:53 UTC, msherman64 reviewed
Looks good to me, thanks!

2022-04-07 14:54 UTC, msherman64 approved these changes

2022-04-11 20:56 UTC, merged