Openstack Exporter - Task #14702
ChameleonCloud/chi-in-a-box pull request #2
Opened 2018-09-04 21:18 UTC by jakecoll

Adds an ansible playbook for extending prometheus monitoring to track metrics from openstack exporter.

2018-09-04 21:33 UTC, diurnalist requested changes
A few notes, mostly about port configuration and how the env file is set up. Also need to watch out for bad Git merges committed. Otherwise, this looks great! 👍

2018-09-04 21:33 UTC, diurnalist commented on inventories/chi_uc/group_vars/openstack_exporter
> +openstack_prometheus_exporter_enable: yes
I think we can get rid of this variable, since including the role == enabling the exporter. It's a bit redundant to keep it for this case.

2018-09-04 21:33 UTC, diurnalist commented on inventories/chi_uc_dev/group_vars/openstack_exporter
> +openstack_prometheus_exporter_enable: yes
Same as `chi_uc`

2018-09-04 21:33 UTC, diurnalist commented on inventories/chi_uc_dev/hosts
> +<<<<<<< HEAD
Looks like a merge conflict here, please resolve before proceeding.

2018-09-04 21:33 UTC, diurnalist commented on roles/openstack_exporter/defaults/main.yml
> +openstack_prometheus_exporter_enable: False
Can remove this pre the prior comments

2018-09-04 21:33 UTC, diurnalist commented on roles/openstack_exporter/defaults/main.yml
> +openstack_prometheus_exporter_project_name: 'openstack'
You don't need quotes here or really for any of the strings; I would remove them for consistency.

2018-09-04 21:33 UTC, diurnalist commented on roles/openstack_exporter/tasks/main.yml
> +
I think you may need to remove this newline, the newline should go after the 'tags' section instead. Not sure how graceful YAML is at parsing this, but it's better to be safe than sorry.

2018-09-04 21:33 UTC, diurnalist commented on roles/openstack_exporter/templates/prometheus_exporter.env-list.j2
> +[client]
This is not valid in a Docker env file, please remove. 

> You can also load the environment variables from a file. This file should use the syntax <variable>=value (which sets the variable to the given value) or <variable> (which takes the value from the local environment), and # for comments.
[source](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file)

2018-09-04 21:33 UTC, diurnalist commented on roles/openstack_exporter/templates/prometheus_exporter.service.j2
> +# {{ ansible_managed }}
FYI, what this does is it adds a header when Ansible writes the file, so an operator that comes later can know that the file was automatically generated (and thus shouldn't be modified directly, as any changes would be overwritten.)

2018-09-04 21:33 UTC, diurnalist commented on roles/openstack_exporter/templates/prometheus_exporter.service.j2
> +ExecStart=/bin/docker run --name=%N \
FYI `%N` means "the name of the systemd service"

2018-09-04 21:33 UTC, diurnalist commented on roles/openstack_exporter/tasks/main.yml
> +        dest: "{{ openstack_prometheus_exporter_config_path }}/env-list"
This is kind of a funny name for this file, I usually do like `{{ *_service_name }}.env` to make it obvious what it is and which service is using it. Can we try to follow that convention?

2018-09-04 21:33 UTC, diurnalist commented on roles/openstack_exporter/templates/prometheus_exporter.service.j2
> +                          --net=host \
I wouldn't use `net=host` for this, rather expose a port explicitly using `--publish`. See [here](https://docs.docker.com/engine/reference/run/#expose-incoming-ports) for more about what this means. Basically we would publish a port (configurable in the role) that binds to whatever port the container uses by default, looks like that is [9103](https://github.com/att-comdev/prometheus-openstack-exporter/blob/master/Dockerfile#L13) in this case. Something like this can accomplish that:

```jinja
--publish {{ openstack_prometheus_exporter_port }}:9103
```

We should avoid `net=host` if we can, I think, as it means the container shares all the same network interfaces as the host OS, which can mean that the container is allowed to talk to more things than it should.

2018-09-06 17:17 UTC, jakecoll commented on roles/openstack_exporter/tasks/main.yml
> +        dest: "{{ openstack_prometheus_exporter_config_path }}/env-list"
yeppers. It's changed.

2018-09-06 21:26 UTC, diurnalist approved these changes
One final comment but I'm giving a prelim 👍 anyways. Nice work

2018-09-06 21:26 UTC, diurnalist commented on roles/openstack_exporter/tasks/main.yml
> +        dest: "{{ openstack_prometheus_exporter_config_path }}/{{ openstack_prometheus_exporter_service_name }}.env"
Can you add a `mode: "0600"` to this and test that it still works? Since this file has secrets in it, it is always best to ensure it can't be read by every user.

2018-09-06 21:39 UTC, jakecoll commented on roles/openstack_exporter/tasks/main.yml
> +        dest: "{{ openstack_prometheus_exporter_config_path }}/{{ openstack_prometheus_exporter_service_name }}.env"
yep, it works.

2018-09-06 21:44 UTC, merged