Hammers
ChameleonCloud/chi-in-a-box pull request #27
Opened 2019-04-24 20:47 UTC by jakecoll

Adds playbook and roles for Hammers

2019-04-24 20:59 UTC, diurnalist requested changes
Can you update this so that the hammers user/password are somehow set in the role?

Also, have a look at the Git history; it looks like a messy merge may have occurred. You could try a `git pull --rebase` on your branch to fix.

2019-04-24 20:59 UTC, diurnalist commented on roles/hammers/tasks/main.yml
> +    name: "{{ hammers_docker_image }}"
Might want to add `force: yes` here to ensure that it re-pulls even if the tag hasn't changed (which it won't if we're always just using `latest` as the tag.)

2019-04-24 20:59 UTC, diurnalist commented on roles/hammers/templates/hammers.env.j2
> +OS_PROJECT_ID={{  }}
typo?

2019-04-24 20:59 UTC, diurnalist commented on roles/hammers/templates/hammers.env.j2
> +OS_USERNAME={{ prometheus_openstack_exporter_user }}
Please do not use variables set outside of your role - instead, do like `{{ hammers_keystone_user }}` and `{{ hammers_keystone_password }}`. Better to keep all the stuff that can affect how a role works internal to the role itself. It will not be obvious to somebody else that changing the prometheus exporter password will require also re-running the hammers provisioning step (so that the password is updated for the containers.)

2019-04-24 20:59 UTC, diurnalist commented on roles/hammers/templates/slack.json.j2
> +    "hostname_names": {
What is this for?

2019-04-24 20:59 UTC, diurnalist commented on roles/hammers/templates/cc-hammer.j2
> +  -v "/root/adminrc:/etc/hammers/adminrc" \
Do you need this if you're already passing in the `hammers_env_file` as environment variables? I'd think only one would be needed (and I think passing in env is the way to go!)

2019-04-24 20:59 UTC, diurnalist commented on roles/hammers/tasks/main.yml
> +    job: "{{ item.cmd }} {{ item.extra_args | default([]) | join(' ') }}"
It seems simpler to just include the entire command on one line, rather than trying to assemble its args in this way. If you don't need to process `extra_args` in any other way, I'd suggest doing that.

2019-04-24 20:59 UTC, diurnalist commented on roles/hammers/tasks/main.yml
> +    dest: /usr/bin/cc-hammer
I'd put this in `/usr/local/sbin`. `/usr/local` is a place for system-wide scripts that are not included as part of the distro (yum). `sbin` is for things that have to run as root -- this script is a candidate because it needs Docker, which requires root.

For a quick read on the difference between all these path conventions, check out [this answer](https://unix.stackexchange.com/a/8658).

2019-04-25 15:17 UTC, jakecoll commented on roles/hammers/templates/slack.json.j2
> +    "hostname_names": {
this is how hammers sends slack notifications.

2019-04-29 15:13 UTC, diurnalist approved these changes
Fix the `--env-file` (it won't work without this, I wouldn't think), but then :shipit: !

2019-04-29 15:13 UTC, diurnalist commented on roles/hammers/templates/cc-hammer.j2
> +docker run -it \
FYI I don't think you need `-i` or `-t` here. `-i` is mostly used when you need to use STDIN (pipe something in to the program or have an interactive input by typing stuff) and `-t` allocates a TTY, which is needed to allow typing as if it's a "regular" console.

2019-04-29 15:13 UTC, diurnalist commented on roles/hammers/templates/cc-hammer.j2
> +  -e "{{ hammers_env_file }}" \
You have to say `--env-file` if you're passing in a file. `-e` (short for `--env`) is for when you're passing in a single variable like `-e 'FOO=bar'`

2019-04-29 15:17 UTC, merged