New Task to create tunelo-calico network/subnet
ChameleonCloud/chi-in-a-box pull request #290
Opened 2024-06-12 06:50 UTC by JOUNAIDSoufiane

Added a task in the k3s playbook to create the tunelo-calico network and the tunelo-calico subnet that are both necessary for the management of hub and spoke ports and the proper functioning of tunelo.

2024-06-12 06:52 UTC, JOUNAIDSoufiane commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix CHI@Edge Chi-in-a-box not creating the tunelo-calico network which is required](https://trello.com/c/Fod5vbZs/3274-fix-chiedge-chi-in-a-box-not-creating-the-tunelo-calico-network-which-is-required)

2024-06-17 22:08 UTC, msherman64 commented on roles/k3s/tasks/config-neutron.yml
> +        auth: "{{ openstack_auth }}"
add `project: "{{ keystone_admin_project }}"`

2024-06-17 22:08 UTC, msherman64 commented on roles/k3s/tasks/config-neutron.yml
> +      module_name: os_subnet
add `project: "{{ keystone_admin_project }}"`

2024-06-21 16:29 UTC, msherman64 requested changes
I would leave the "{{ physical_network_calico }}" and "{{ physical_network_tunelo }}" hardcoded for now. 
I'll add templating for them when I refactor the post-deploy network creation, as it's not useful before then. (can't make two different flat networks on the same physnet, so need to template everything else)

Otherwise LGTM

2024-06-25 20:57 UTC, merged